---
- name: Create Directory | awscli | /root/.aws
  file:
    state: directory
    path: /root/.aws

- name: Upload Config | awscli | configuration
  template:
    src: "root/.aws/{{ item }}"
    dest: "/root/.aws/{{ item }}"
  with_items:
    - config
    - credentials
  tags:
    - configuration
    - template-configuration
